export const HEALTHCARECOST_LOADING = 'HEALTHCARECOST_LOADING'
export const HEALTHCARECOST_FAILED = 'HEALTHCARECOST_FAILED'
export const ADD_HEALTHCARECOST = 'ADD_HEALTHCARECOST'


export const HCPCSOPERATION_LOADING = 'HCPCSOPERATION_LOADING'
export const HCPCSOPERATION_FAILED = 'HCPCSOPERATION_FAILED'
export const ADD_HCPCSOPERATION = 'ADD_HCPCSOPERATION'


export const USSTATES_LOADING = 'USSTATES_LOADING'
export const USSTATES_FAILED =  'USSTATES_FAILED'
export const ADD_USSTATES = 'ADD_USSTATES'
