export const HEALTHCARECOST_LOADING = 'HEALTHCARECOST_LOADING'
export const HEALTHCARECOST_FAILED = 'HEALTHCARECOST_FAILED'
export const ADD_HEALTHCARECOST = 'ADD_HEALTHCARECOST'


export const HCPCSOPERATION_LOADING = 'HCPCSOPERATION_LOADING'
export const HCPCSOPERATION_FAILED = 'HCPCSOPERATION_FAILED'
export const ADD_HCPCSOPERATION = 'ADD_HCPCSOPERATION'


export const USSTATES_LOADING = 'USSTATES_LOADING'
export const USSTATES_FAILED =  'USSTATES_FAILED'
export const ADD_USSTATES = 'ADD_USSTATES'


export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const USERPROFILE_LOADING = "USERPROFILE_LOADING"
export const USERPROFILE_FAILED = "USERPROFILE_FAILED"
export const USERPROFILE_SUCCESS = "USERPROFILE_SUCCESS"

export const USEROPERATION_LOADING = 'USEROPERATION_LOADING'
export const USEROPERATION_FAILED = 'USEROPERATION_FAILED'
export const ADD_USEROPERATION = 'ADD_USEROPERATION'
